export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'


export const LOGIN_START = 'LOGIN_START'
export const lOGIN_SUCCESS = 'lOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const LOGIN_GOOGLE_START = 'LOGIN_GOOGLE_START'
export const lOGIN_GOOGLE_SUCCESS = 'lOGIN_GOOGLE_SUCCESS'
export const LOGIN_GOOGLE_ERROR = 'LOGIN_GOOGLE_ERROR'

export const LOGIN_FACEBOOK_START = 'LOGIN_FACEBOOK_START'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR'

export const SET_USER = 'SET_USER'

